version: '3.6'

services: 
    db:
        image: mariadb
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: peliculas
            MYSQL_USER: user
            MYSQL_PASSWORD: user
    
        volumes: 
            - ./init:/docker-entrypoint-initdb.d
        ports:
            - "3306:3306"

    adminer:
        image: adminer
        restart: always
        ports: 
            - 8080:8080