//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "Actores")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_actor: i32,
    pub nombre: Option<String>,
    pub fecha_nacimiento: Option<Date>,
    pub nacionalidad: Option<String>,
    pub id_pelicula: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::peliculas::Entity",
        from = "Column::IdPelicula",
        to = "super::peliculas::Column::IdPelicula",
        on_update = "Restrict",
        on_delete = "Restrict"
    )]
    Peliculas,
}

impl Related<super::peliculas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Peliculas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
