//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Directores")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_director: i32,
    pub nombre: Option<String>,
    pub fecha_nacimiento: Option<Date>,
    pub nacionalidad: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::peliculas::Entity")]
    Peliculas,
}

impl Related<super::peliculas::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Peliculas.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
