//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub use super::actores::Entity as Actores;
pub use super::comentarios::Entity as Comentarios;
pub use super::directores::Entity as Directores;
pub use super::peliculas::Entity as Peliculas;
pub use super::usuarios::Entity as Usuarios;
