//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "Usuarios")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id_usuario: i32,
    pub nombre: Option<String>,
    pub correo_electronico: Option<String>,
    pub contrasena: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::comentarios::Entity")]
    Comentarios,
}

impl Related<super::comentarios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Comentarios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
